import os
MQTT_HOST = os.getenv("MQTT_HOST", "192.168.0.253")
MQTT_PORT = int(os.getenv("MQTT_PORT", 1883))
MQTT_USERNAME = os.getenv("MQTT_USERNAME", "emeraldhills110")
MQTT_PASSWORD = os.getenv("MQTT_PASSWORD", "emeraldhills110")
MQTT_DYNALITE_PREFIX = os.getenv("MQTT_DYNALITE_PREFIX", "dynalite")
MQTT_CLIMATE_STATE  = os.getenv("MQTT_CLIMATE_STATE", "homeassistant/climate/+/state") 
MQTT_CLIMATE_PREFIX = os.getenv("MQTT_CLIMATE_PREFIX","homeassistant/climate")
MQTT_BRIDGE_WILL =  os.getenv("MQTT_BRIDGE_WILL", "bridges/climate_dynalite") 
MQTT_DEBUG =  os.getenv("MQTT_DEBUG", False) 
OUT_JOIN = os.getenv("OUT_JOIN", 0xFE) 
IN_JOIN = os.getenv("OUT_JOIN", 0xFF) 
TEMP_PRECISION = os.getenv("TEMP_PRECISION", 0)